#!/bin/bash
set -e

database="${POSTGRES_DB:-fantasy}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$database" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS account AUTHORIZATION ${POSTGRES_USER};
    CREATE SCHEMA IF NOT EXISTS player AUTHORIZATION ${POSTGRES_USER};
    CREATE SCHEMA IF NOT EXISTS game_data AUTHORIZATION ${POSTGRES_USER};

    GRANT ALL ON SCHEMA account TO ${POSTGRES_USER};
    GRANT ALL ON SCHEMA player TO ${POSTGRES_USER};
    GRANT ALL ON SCHEMA game_data TO ${POSTGRES_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA account
    GRANT ALL ON TABLES TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA account
    GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA player
    GRANT ALL ON TABLES TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA player
    GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA game_data
    GRANT ALL ON TABLES TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA game_data
    GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};
EOSQL
